# Generated by Django 4.1.4 on 2022-12-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at']},
        ),
    ]
