# Generated by Django 4.1.4 on 2022-12-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
